### ISSUE TITLE
Optical Inter-domain Links

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#1]
Should we consider the scenarios where there are inter-domain links also between Optical domains?

The current assumption (to be validated) says:

> Inter-domain links exist only between Packet domains (i.e., between ASBR routers) and between Packet and Optical domains (i.e., between routers and ROADMs). In other words, there are no inter-domain links between Optical domains

**Comment by jbouqui153** [comment]
On my side I think it is reasonable to make this assumption at the beginning. Then their may be lots of different implementation variants depending whether the scenario is for mobile, fixed or enterprise...

**Comment by italobusi** [comment]
This issue is relevant for section 2 and 3.1

**Comment by italobusi** [comment]
This issue seems already address in the latest editors' draft (after PR#26)

@ZhengYanlei , @FabioPeruzzini , @jbouqui153 : are you ok?

**Comment by jbouqui153** [comment]
Yes, we can close this issue #1 in my opinion
