### ISSUE TITLE
IP services and relationship with "draft-lee-teas-actn-poi-applicability-00"

### ISSUE THREAD

**Issue by FabioPeruzzini** [FabioPeruzzini/actn-poi#10]
In our draft, we speak about IP services because in some use cases, it is mandatory that MDSC knows them.
So I propose to insert a reference to draft "draft-lee-teas-actn-poi-applicability-00" which is more focused on IP services.

What do you think?

**Comment by michael-scharf** [comment]
By IP services you mean L3VPNs, VPLS, EVPN, etc.?

I do not fully understand why an MDSC would need to know such services, at least in an MPLS (or segment routing) IP network. In think an MDSC can handle a lot of use cases if the MDSC is just aware of MPLS LSPs. Understanding which IP services run on the MPLS LSPs is by and large an IP-only problem orthogonal to POI - at least to me.

Also, keep in mind that the numbers of IP services over a single MPLS LSP can be huge, and an MDSC that knows all IP services in a bigger IP network may have to understand hundreds of thousands of IP services, or even more. At least to my understanding, scalability needs to be considered from day one when discussion awareness of IP services.

Personally, I would suggest to first focus on "IP links", IGP adjacencies, and MPLS LSPs on routers. That alone already is not trivial to deal with.
