### ISSUE TITLE
Authors in the front page

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#17]
Comment from @danielkinguk : https://github.com/FabioPeruzzini/actn-poi/commit/68e837ac44ed3330a2303ec3fcb32eda4e8bbc2b

> We should add Authors from draft-lee-teas-actn-poi-applicability on the front page. Maybe have Fabio and Young on the front page with (Editor) after their names, and move everyone else to Author section.

**Comment by italobusi** [comment]
**2020-04-27 Call**

Proposal (from @FabioPeruzzini ):
Fabio Peruzzini
Jean-Francois Bouquier
Italo Busi
Daniel King
one TBD author from draft-lee-teas-actn-poi-applicability

@FabioPeruzzini : check which author from draft-lee-teas-actn-poi-applicability to move to the front page

**Comment by FabioPeruzzini** [comment]
Update proposal
Fabio Peruzzini
Jean-Francois Bouquier
Italo Busi
Daniel King
Daniele Ceccarelli.

**Comment by FabioPeruzzini** [comment]
> @FabioPeruzzini : check which author from draft-lee-teas-actn-poi-applicability to move to the front page

I would propose to move Daniele Ceccarelli in the front page  since he has contributed to the merging of the two drafts

**Comment by italobusi** [comment]
Addressed with https://tools.ietf.org/html/draft-peru-teas-actn-poi-applicability-05
