### ISSUE TITLE
Description of the Discovery Scenario

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#18]
Review the description of the discovery scenario in section 3.1 of the draft

**Comment by jbouqui153** [comment]
Propose to decide first the proposal for new table of content in #6 as it would modify the use cases (being more service focussed but including also the underlying transport configuration when required)

**Comment by jbouqui153** [comment]
In the new structure I already proposed the text for discovery scenario.  Need to be reviewed by all in #28
