### ISSUE TITLE
Review of the Discovery Scenario Description

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#19]
Review the analysis of the discovery scenario in section 3.1.1 of the draft

**Comment by ggalimba56** [comment]
If the Packet layer is connected to the DWDM (wson/soon) layer via grey interfaces (e.g. 100GE, etc) the 3.1.1 section properly describes the scenario.
In this case there is a clear separation between Packet and Optical layers and the interconnection between the two layer is a Ethernet service.
In case the DWDM interface is located into the Router, the demarcation between Packet and Optical layer is becoming  more complex as the Optical channel is terminated by the Router.
In this case the models supported by the Routers must include some WSON topology models  (at least the models describing the DWDM interface - aka DWDM pluggable).
As such the draft should include also this scenario description and the modelling supporting it.

**Comment by italobusi** [comment]
**[2022-06-21 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-06-21.md)**

Jeff has provided a set of comments: https://github.com/FabioPeruzzini/actn-poi/issues/19#issuecomment-1136120930

- [ ] @italobusi : review and proposed resolutions for the comments
