### ISSUE TITLE
JSON and XML encoding in RESTCONF

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#2]
Check if there is interop between JSON and XML encoding

RESTCONF defines both JSON and XML encoding. If there is no interop, it might be useful to indicate which encoding should be used for achieving interop

As far as I am aware of, most of the RESTCONF implementations use JSON

**Comment by jbouqui153** [comment]
Yes, fully agree. Let specify JSON encoding

**Comment by italobusi** [comment]
Closed in https://tools.ietf.org/html/draft-ietf-teas-actn-poi-applicability-01#section-3.1
