### ISSUE TITLE
DWDM routers interfaces

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#20]
DWDM interfaces on the routers are not covered by the current draft

Check the relevance/importance to cover them in future versions of the draft and/or in future RFCs

**Comment by ggalimba56** [comment]
The DWDM interfaces fitter in routers are becoming more and ore relevant for the operators for many reasons:
- Availability of small form factor pluggable interfaces like QSFP-SS ZR 400G
- The possibility to fit the above pluggable in the salo slot of 400GE long reach
- Dramatic cost reduction compare to the traditional DWDM interfaces and CFP-2
- Cost saving eliminating Transponder in DWDM equipment
- Clear specification (standardisation) of New pluggable facilitate the interoperability song different vendors

**Comment by italobusi** [comment]
**2020-05-25 Call**

We have agreed to mention that the cases of colored interfaces on the routers is out of scope from this draft

@ggalimba56 : please propose some text for a paragraph to clarify this point

**Comment by ggalimba56** [comment]
Although the new technologies (e.g. QSFP-DD ZR 400G) are making convenient to fit the DWDM pluggable interfaces on the Routers, the deployment of those pluggable is not yet widely adopted by the operators. The reason is that most of operators are not yet ready to collapse the multilayer networks in a single layer and reorganise the Packet and Transport departments.
As a consequence this draft is not addressing the scenario where optical components are shared under different administrative domains.  
This matter will be described in a different draft.

**Comment by ggrammel** [comment]
We then would need to spell out what an "administrative domain" refers to. The current draft talks about "domains" but does not use the term "administrative domain". It's also not clear to me what "collapse multilayer networks in a single layer" would mean. My suggestion is to re-phrase:

> Although the new technologies (e.g. QSFP-DD ZR 400G) are making convenient to fit the DWDM pluggable interfaces on the Routers, the deployment of those pluggable is not yet widely adopted by the operators. The reason is that most of operators are not yet ready to manage Packet and Transport networks in a unified single domain. As a consequence, this draft is not addressing the unified scenario. This matter will be described in a different draft.

**Comment by ggalimba56** [comment]
Thanks for the note Gert,

I agree with the modification.
Shall we consider to clarify the administrative domain meaning?
Let’s briefly talk today.

Best Regards,

Gabriele

[http://www.cisco.com/swa/i/logo.gif]

Gabriele Galimberti
Principal Engineer
Cisco Photonics Srl
Italy

via S.Maria Molgora, 48 C
20871 - Vimercate (MB)
Italy
www.cisco.com/global/IT/<http://www.cisco.com/global/IT/>

ggalimbe@cisco.com<mailto:ggalimbe@cisco.com>
Phone :+39 039 2091462
Mobile :+39 335 7481947
Fax :+39 039 2092049

**Comment by italobusi** [comment]
Reference RFC8453 for the domain definition and generalize the IP domain definition to cover also multi-area and not only multi-AS scenarios.

@ggalimba56 : provide some text proposal to clarify this point
