### ISSUE TITLE
LLDP snooping

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#39]
Describe the case where LLDP snooping is not supported: either static or proprietary solution.

Is it possible to run LLDP between the router and the ROADM?

**Comment by italobusi** [comment]
**2021-01-12 Ad-hoc call**

An issue with LLDP snooping is that this protocol is not described in any standard document.
It would be good to have at least some Informational RFC in the routing WG to be referenced for the LLDP snooping functionality.

It may be worthwhile providing some vendor-specific documentation.

**Comment by jefftant** [comment]
LLDP snooping by different vendors references:
Cisco NCS: https://www.cisco.com/c/en/us/td/docs/optical/ncs1000/60x/dwdm-configuration-guide-60x/dwdm-configuration-guide-60x_chapter_01.html
Juniper BTI78000: https://www.juniper.net/documentation/en_US/bti-series/bti78004.1/topics/concept/concept-c-7800-swicg-lldp.html

**Comment by michael-scharf** [comment]
References for Nokia:

- Solution for IP/optical integrationn: https://pf.content.nokia.com/t004ok-webscale-ip-optical-integration/multilayer-topology-use-case
- Datasheet for the Nokia 1830 PSI: https://onestore.nokia.com/asset/f/201662

**Comment by italobusi** [comment]
Need to update the text in the draft

**Comment by italobusi** [comment]
**2021-09-14 ACTN POI Call (Slot 2)**

Check with the TEAS WG how to deal with the informative references on LLDP snooping.

**Comment by italobusi** [comment]
> **2021-09-14 ACTN POI Call (Slot 2)**
> 
> Check with the TEAS WG how to deal with the informative references on LLDP snooping.

Mail sent: https://mailarchive.ietf.org/arch/msg/teas/XAQrQdtoOLvzol13VmKmWNimo-w/

**Comment by ggalimba56** [comment]
What is described by Brent is correct. 
Trying to answer to other questions:
3. Correct, the Optical node parses only the LLDP packets receives on the Local (client) TXP port.
4. Exactly, the connection can be detected before loading the port with services. This is specially important when there is GMPLS and UNI between the two (but is not our case).
5. in case od SDN controller the P-PNC does not know (a priori) whether the (gray) Ethernet interface is connected to a TXP or a Router.   The MDSC should know that as is responsible to build the multilayer network topology detecting the interlayer links (thanks also to LLDP).

**Comment by italobusi** [comment]
> * [ ]  @italobusi  provide more details on the issue with plug-id and check with the TE Topology model (RFC8795) authors for some guidance

See text proposed in section 4.2.2 and 4.2.3 of https://github.com/FabioPeruzzini/actn-poi/pull/69/commits/c31070a1a559db44c050324fff795f3c1ae45f02

**Comment by italobusi** [comment]
> * [x]  @italobusi  provide more details on the issue with plug-id and check with the TE Topology model (RFC8795) authors for some guidance

See PR #69
