### ISSUE TITLE
Request TEAS WG chairs to update the TEAS Webex calls

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#49]
New plan:
- May 4th at 5pm CEST (Slot 2)
- May 11th at 10:30am CEST (Slot 1)
- May 18th at 5pm CEST (Slot 2)
- May 25th at 10:30am CEST (Slot 1)

Slot 2 is US friendly and slot 1 is China friendly

https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2021-04-27.md

**Comment by italobusi** [comment]
Mail sent on 2021-04-28: waiting for the new TEAS WG call details to be sent on the TEAS WG mailing list

**Comment by ggalimba56** [comment]
Thanks Italo,

I think the calendar should be updated asap as slot 1 and 2 will be swapped compare to the current outlook.

Thanks a lot,

Regards,

Gabriele

From: italobusi ***@***.***>
Reply to: FabioPeruzzini/actn-poi ***@***.***>
Date: Monday, 3 May 2021 at 10:05
To: FabioPeruzzini/actn-poi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [FabioPeruzzini/actn-poi] Request TEAS WG chairs to update the TEAS Webex calls (#49)


New plan:

  *   May 4th at 5pm CEST (Slot 2)
  *   May 11th at 10:30am CEST (Slot 1)
  *   May 18th at 5pm CEST (Slot 2)
  *   May 25th at 10:30am CEST (Slot 1)

Slot 2 is US friendly and slot 1 is China friendly

https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2021-04-27.md
