### ISSUE TITLE
Provisioning of LAG

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#5]
The scenario in section 2 describing the IP Link requires further analysis for the LAG setup

It seems that the intention is to be able to setup an IP link supported by two or more “parallel” connections within the DWDM network, between two or more ETH links pairs. It is also desirable to be able to add a second connection after the first one has been established (bandwidth increase)

**Comment by FabioPeruzzini** [comment]
I agree with your comment.
The new use case 1.5 I think addresses this point.
Do you agree?

**Comment by italobusi** [comment]
The use case 1.5 clarifies the requirement "to be able to add a second connection after the first one has been established (bandwidth increase)"

I am still not sure whether the requirement is to configure a LAG (including all the LAG attributes defined by IEEE 802.1AX) or just an IP link supported by one or more "parallel" connections within the DWDM network

**Comment by michael-scharf** [comment]
I believe it matters whether the LAG is handled by the router, or inside transport switches.

If the LAG is implemented in the router, the DWDM network may just have to provide OTN or ETH services with co-routing constraints, i.e., OTN or ETH services in the transport network may need to be strictly co-routed or, alternatively, fully SRLG-disjoint. That may be the simpler case as it just comes down to LAG provisioning in the router, which an IP management system ("controller") should be able to do. One "IP link" over a LAG then maps to serveral transport services (e.g., ETH or OTN).

I think there are some optical transport devices with Ethernet switching capabilities, and such optical devices may be able to implement a LAG in the transport network, too. That use case may be more complex for several reasons.

**Comment by italobusi** [comment]
[**2022-01-18 ACTN POI Call (Slot 1)**](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-01-18.md)

LAG was useful few years ago to expand capacity with 10G links but LAG is no longer an important feature with current high capacity interfaces (100G and above), so it could be removed

Swamy: how to increase capacity with 100G links?

Jeff: are you considering LAG for 100G interfaces?

- [ ] Jeff/Fabio: to check whether LAG is still a priority for high capacity interfaces (100G and above)

Victor: out of scope for this current version or out of scope of this document?

Agreement to keep LAG out of scope for this draft version (draft PR #69) and to add it in a later revision of the document before WG LC

**Comment by italobusi** [comment]
**2022-01-25 ACTN POI Call (Slot 2)**

> * [x]  Jeff/Fabio: to check whether LAG is still a priority for high capacity interfaces (100G and above)

Jeff: in general it is not really recommended to have LAG on NNI interfaces (between routers) and with the evolution beyond 100G, LAG is not recommended

Fabio: use LAG between routers and WDM only to increase the bandwdith and not for resiliency. To be further investigated if LAG is used between routers

The agreement to keep LAG out of scope for this draft version (draft PR #69) and to add it in a later revision of the document before WG LC has been confirmed. Need to furhter investigate whether to describe the use of LAG  only for multi-layer IP links or also for direct interconnection between routers

- [ ] @FabioPeruzzini : to check if LAG is used also between routers

**Comment by italobusi** [comment]
[2022-04-26 ACTN POI Call (Slot 1)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-04-26.md)

Reviewed and discussed some of the open issues in PR #90

It is possible that within the same P-PNC domains LAG and non-LAG links co-exist: need to find a solution to allow the P-PNC know whether a Ethernet link that is discovered or configured by the MDSC is intended to support an IP Link or to be used within a LAG

Further investigation is needed about the need to support the configuration of the LAG after the IP link has been created without LAG since it is possible to create a LAG with only one member to be able to add new members in the future

- [ ] Jeff/Italo: To check about the requirement to support the configuration of the LAG after the IP link has been created without LAG

**Comment by italobusi** [comment]
**[2022-05-10 ACTN POI Call (Slot 1)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-05-10.md)**

> - [x] @FabioPeruzzini : to check if LAG is used also between routers

> - [x] @jbouqui153 / @italobusi : To check about the requirement to support the configuration of the LAG after the IP link has been created without LAG

Italo has checked offline with Fabio:
- LAG can be used also between routers (i.e., on single-layer ETH links);
- within the same P-PNC domain, links with and without LAG can co-exist: when setting up a new multi-layer IP link, the MDSC decides whether it should use or not LAG;
- it could be possible that LAG can be configured also after the IP link has been setup without LAG.

Proposal:
- describe the discovery of the LAG for any (single-layer and multi-layer) intra-domain link, since the mechanism is the same;
- mention that LAG can also be used on inter-domain links but do not describe the discovery of LAG on inter-domain links since it has no multi-layer aspects (out-of-scope);
- describe the setup of the LAG for multi-layer intra-domain links only and update the procedure describe in the current draft to allow the co-existence of IP links with and without LAG:
  - after a multi-layer ETH link is discovered/configured, the P-PNC has not enough information to know whether the MDSC intention is to support an IP link over this ETH link or to create a new LAG group using this ETH link or to add this ETH link to an existing LAG group: as a consequence, the discovery/configuration of the ETH link is not sufficient to trigger the P-PNC to configure an IP link (as written in the current draft);
  - the MDSC can trigger the P-PNC to configure an IP link by creating this IP link, within the IP topology at the MPI, without configuring it: this would trigger the P-PNC to configure the IP link
- describe the procedure to setup a LAG also after the IP link has been created.

Need to clarify in the draft whether all the information that is needed to trigger the P-PNC to configure a new IP link is available, at the MPI, in the current YANG models

- [ ] Swamy: to further investigate the YANG models at the MPI that could be used to trigger P-NC to setup a new IP link

Jeff: usually when LAG is desired, a LAG group with one link is created to allow adding new members when needed. Adding LAG after the IP link is setup is a quite disruptive process. The scenario to add LAG after the IP link is setup is a niche use case

Agreement to mention the option but not to describe it in details
