### ISSUE TITLE
Provide an ASCII art version of the L3VPN reference network

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#53]
Gabriele: provide an ASCII art version of the figure in section 4.2 of [Issue #38--847723866](https://github.com/FabioPeruzzini/actn-poi/issues/38#issuecomment-847723866) to be incorporated in the next version of the I-D

**Comment by ggalimba56** [comment]
Here attached the txt files describing the L3VPN txt drawing.
I'd need to work more to make it more comprehensible ant to limit the row to 69 Characters.


[Multilayer-multidomain-txt.txt](https://github.com/FabioPeruzzini/actn-poi/files/6649754/Multilayer-multidomain-txt.txt)

**Comment by danielkinguk** [comment]
Hi folks, I had a go with the ASCII art too.

[Multilayer-Multidomain-dk.txt](https://github.com/FabioPeruzzini/actn-poi/files/6693346/Multilayer-Multidomain-dk.txt)

A little less complicated, and fits with character limitations.

**Comment by ggalimba56** [comment]
I like it !

Ciao,

Gab.

From: danielkinguk ***@***.***>
Reply to: FabioPeruzzini/actn-poi ***@***.***>
Date: Tuesday, 22 June 2021 at 12:22
To: FabioPeruzzini/actn-poi ***@***.***>
Cc: Gabriele Galimberti ***@***.***>, Assign ***@***.***>
Subject: Re: [FabioPeruzzini/actn-poi] Provide an ASCII art version of the L3VPN reference network (#53)


Hi folks, I had a go with the ASCII art too.

Multilayer-Multidomain-dk.txt<https://github.com/FabioPeruzzini/actn-poi/files/6693346/Multilayer-Multidomain-dk.txt>

A little less complicated, and fits with character limitations.

**Comment by italobusi** [comment]
@danielkinguk @ggalimba56 : thanks for the Figure

Few comments from the review during yesterday ad-hoc call:
1. Update the SR policy paths to show the intra-domain PE13-P16-P14 and inter-domain PE13-BR11-BR12-P24-PE23 paths
2. No need to show the TI-LFA in this figure.

**Comment by italobusi** [comment]
An additional comment: for some strange reasons, the underscore "_" characters are not shown in the word document

It is not a major issue since it seems the underscore "_" characters are present in the prn and txt files generated from the word document but the word document would be easier to read if the underscore "_" characters are replaced by dash "-" or "=" or other characters (if possible)
