### ISSUE TITLE
Multi-domain SR-TE with binding SID

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#54]
Describe the scenario of an end-to-end SR-TE path with binding SID

See: https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2021-06-01.md

**Comment by jbrentfoster** [comment]
Updated slides showing BSID scenarios
[ACTN_MDSC_Interdomain_SR_2.0.pptx](https://github.com/FabioPeruzzini/actn-poi/files/6665757/ACTN_MDSC_Interdomain_SR_2.0.pptx)
