### ISSUE TITLE
Local protection with TI-LFA

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#56]
provides some slides to describe how TI-LFA can take into account multi-layer SRLG disjointness, providing that SRLG information is provided by the O-PNCs to the P-PNC thought the MDSC

Note: the target is to discuss TI-LFA after IETF-111

**Comment by jbrentfoster** [comment]
Adding slides for TI-LFA tutorial including SRLG behavior
[TI-LFA_TOI.1.0.pptx](https://github.com/FabioPeruzzini/actn-poi/files/7204870/TI-LFA_TOI.1.0.pptx)
.

**Comment by italobusi** [comment]
2021-09-14 ACTN POI call (Slot 1)

https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2021-09-21.md

- [ ] @italobusi  update the draft text based on the analysis and request Brent and Jeff B. to review the text

**Comment by italobusi** [comment]
> * [x]  @italobusi  update the draft text based on the analysis and request Brent and Jeff B. to review the text

See proposed text for section 4.2 and 4.3 in https://github.com/FabioPeruzzini/actn-poi/pull/69/commits/c31070a1a559db44c050324fff795f3c1ae45f02

**Comment by italobusi** [comment]
> * [x]  @italobusi  update the draft text based on the analysis and request Brent and Jeff B. to review the text
> 
> https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2021-09-21.md

See PR #69
