### ISSUE TITLE
Editorial Review of I-D

### ISSUE THREAD

**Issue by danielkinguk** [FabioPeruzzini/actn-poi#59]
Provide a full review before July 6.

**Comment by italobusi** [comment]
@danielkinguk : we are still finalizing the draft text. Please wait for my green flag (tonight or tomorrow, the latest).

**Comment by italobusi** [comment]
@danielkinguk : we have finished working on the draft. Please review the latest version on the master branch: https://github.com/FabioPeruzzini/actn-poi/commit/c57d972363297fd0802ce61a76182d0bbb065840

**Comment by danielkinguk** [comment]
Just uploaded a new version of the document in the master branch with changemarkers enabled.
