### ISSUE TITLE
Review current L3VPN text

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#67]
**2021-09-14 ACTN POI Call (Slot 2)**

Review current L3VPN text to check if anything is missing or requires clarification, in particular the analysis of the YANG data models to be used at the MPI and if there are any gaps

_Originally posted by @italobusi in https://github.com/FabioPeruzzini/actn-poi/issues/38#issuecomment-920675893_

**Comment by jbrentfoster** [comment]
regarding this note:

   [Editor's Note] Further investigation is needed to understand how
   the binding between a L3VPN and this new end-to-end SR-TE path can
   be configured.

This is covered exhaustively in section 8 of draft-ietf-spring-segment-routing-policy
https://datatracker.ietf.org/doc/html/draft-ietf-spring-segment-routing-policy-08#section-8

8.4 Per-Destination Steering 

would be the preferred mechanism for this use-case

**Comment by italobusi** [comment]
[2021-11-23 ACTN POI Call (Slot 1)
](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2021-11-23.md)

Per-destination steering (section 8.4 of draft-ietf-spring-segment-routing-policy-08) describes the behavior used by the ingress PE to steer the ingress traffic to an SR policy

Jeff: in TSM, it is possible to indicate the SR policy for a LxVPN

It seems the relationship between TE tunnel and SR policy in TSM

More investigation is needed to understand the relationship between TE tunnel and SR policy YANG models and their usage with TSM

There is an on-going discussion within the TEAS WG modelling team about this:

https://github.com/tsaad-dev/te/issues/172

- [ ] #72

**Comment by italobusi** [comment]
**[2022-11-22 ACTN POI Call (Slot 1)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-11-22.md)**

Closed. the whole document will be reviewed again before WG LC
