### ISSUE TITLE
Introduction 

### ISSUE THREAD

**Issue by FabioPeruzzini** [FabioPeruzzini/actn-poi#7]
Introduction with focus on the utilities of IP-DWDM integration

**Comment by michael-scharf** [comment]
I will come up with text this week. Sorry for the delay.

**Comment by michael-scharf** [comment]
Below is my proposed wording for an introduction, from the point of a former product line manager in this space who had to bridge the gap between these two "worlds". I post the text here to facilitate a discussion.

1.  Introduction

Packet Optical Integration (POI) is an advanced use case of traffic engineering. In wide area networks, a packet network based on the Internet Protocol (IP) and possibly Multiprotocol Label Switching (MPLS) is typically realized on top of an optical transport network that uses Dense Wavelength Division Multiplexing (DWDM). In many existing network deployments, the packet and the optical networks are engineered and operated independently of each other. There are technical differences between the technologies (e.g., routers vs. optical switches) and the corresponding network engineering and planning methods (e.g., inter-domain peering optimization in IP vs. dealing with physical impairments in DWDM, or very different time scales). In addition, customers and customer needs can be different between a packet and an optical network, and it is not uncommon to use different vendors in both domains. Last but not least, state-of-the-art packet and optical networks use sophisticated but complex technologies, and for a network engineer it may not be trivial to be a full expert in both areas. As a result, packet and the optical network are often operated in technical and organizational silos.

This separation is inefficient for many reasons. Both capital expenditure (CAPEX) and operational expenditure (OPEX) could be significantly reduced by better integrating the packet and the opical network. Multi-layer topology insight can speed up troubleshooting (e.g., alarm correlation) and network operation (e.g., coordination of maintenance events), multi-layer topology inventory can improve service quality (e.g., detection of diversity constraint violations) and multi-layer traffic engineering can use the available network capacity more efficiently (e.g., coordination of restoration). In addition, provisioning workflows can be simplified or automated as needed across layers (e.g, to achieve bandwidth on demand).

Fully leveraging these benefits requires an integration between the management and control of the packet and the optical network. The Abstraction and Control of TE Networks (ACTN) framework defines functions and interfaces between Multi-Domain Service Coordinator (MDSC) and Provisioning Network Controller (PNC) that can be used for coordinating the packet and optical layers.

In this document, key use cases for Packet Optical Integration (POI) are described both from the point of view of the optical and the packet layer. The objective is explain the benefit and the impact for both the packet and the optical layer, and to identify the required interaction between both layers. Precide definitions of use cases can help with achieving a common understanding across different disciplines. The focus of the use cases are IP networks operated as client of optical DWDM networks. The use cases are ordered by increasing level of integration and complexity. For multi-layer each use case, the document analyzes how to use the interfaces and data models of the ACTN architecture. Understanding the standardization and potential gaps helps to assess the feasibility of integration between packet and optical layers, in particular in multi-vendor environments.

**Comment by sergiobelotti** [comment]
Hi Michael, I like a lot your text, that in my view exactly represent the scenario related of POI, with the benefits to have this integration. I have only one question , realted to one of these advantages and it is the sentence regarding the service quality improvement derived from an efficient multi-layer inventory : it is clear the link of service quality and knowledge of diversity constraints violation. Less clear , for me, the direct relationship with inventory. Is it not still related to multi-layer topology insight ? Just my doubt for clarification.

**Comment by michael-scharf** [comment]
Hi Sergio,

Good question. Indeed, it may be difficult to clrearly distinguish both
cases. But there is a subtle detail behind my wording:

First, there are 'navigation' use cases in which one mainly performs
top-down or buttom-up navigation between the layers. This typically starts
from some given entity. An example is to identify all 'IP links' over a
given OTS link or ODU service. This is often an online operation as part of
a human workflow in the NOC.

Second, there are use cases for 'analysis' operations running over the
whole multi-layer topology inventory database. These can be batch processes
running offline and generating reports (e.g. over night). In that case, the
operation is not triggered by an engineer.

Maybe one could add some words (say, 'online' vs. 'offline') to better
explain that. For sure, it is a subtle difference and one could also merge
them, albeit they are quite different to the user of the solution.

Does that make sense?

Michael




sergiobelotti <notifications@github.com> schrieb am Mi., 23. Okt. 2019,
10:49:

**Comment by sergiobelotti** [comment]
Hi Michael, thanks for explanation.
I think it does make sense , no doubt.
Your two examples of distinction are clear: are the two different cases also imply different speed of reaction in the analysis , e.g. alarm-correlation can call a more fast action in the user. If yes we could also add this aspect together with on-line and off-line .

Sergio

**Comment by michael-scharf** [comment]
New proposal wih Sergio's feedback:

1.   Introduction

Packet Optical Integration (POI) is an advanced use case of traffic engineering. In wide area networks, a packet network based on the Internet Protocol (IP) and possibly Multiprotocol Label Switching (MPLS) is typically realized on top of an optical transport network that uses Dense Wavelength Division Multiplexing (DWDM). In many existing network deployments, the packet and the optical networks are engineered and operated independently of each other. There are technical differences between the technologies (e.g., routers vs. optical switches) and the corresponding network engineering and planning methods (e.g., inter-domain peering optimization in IP vs. dealing with physical impairments in DWDM, or very different time scales). In addition, customers and customer needs can be different between a packet and an optical network, and it is not uncommon to use different vendors in both domains. Last but not least, state-of-the-art packet and optical networks use sophisticated but complex technologies, and for a network engineer it may not be trivial to be a full expert in both areas. As a result, packet and optical networks are often operated in technical and organizational silos.

This separation is inefficient for many reasons. Both capital expenditure (CAPEX) and operational expenditure (OPEX) could be significantly reduced by better integrating the packet and the opical network. Multi-layer online topology insight can speed up troubleshooting (e.g., alarm correlation) and network operation (e.g., coordination of maintenance events), multi-layer offline topology inventory can improve service quality (e.g., detection of diversity constraint violations) and multi-layer traffic engineering can use the available network capacity more efficiently (e.g., coordination of restoration). In addition, provisioning workflows can be simplified or automated as needed across layers (e.g, to achieve bandwidth on demand).

Fully leveraging these benefits requires an integration between the management and control of the packet and the optical network. The Abstraction and Control of TE Networks (ACTN) framework defines functions and interfaces between Multi-Domain Service Coordinator (MDSC) and Provisioning Network Controller (PNC) that can be used for coordinating the packet and optical layers.

In this document, key use cases for Packet Optical Integration (POI) are described both from the point of view of the optical and the packet layer. The objective is explain the benefit and the impact for both the packet and the optical layer, and to identify the required interaction between both layers. Precide definitions of use cases can help with achieving a common understanding across different disciplines. The focus of the use cases are IP networks operated as client of optical DWDM networks. The use cases are ordered by increasing level of integration and complexity. For multi-layer each use case, the document analyzes how to use the interfaces and data models of the ACTN architecture. Understanding the standardization and potential gaps helps to assess the feasibility of integration between packet and optical layers, in particular in multi-vendor environments.

**Comment by sergiobelotti** [comment]
Hi Michael, I like the update.
