### ISSUE TITLE
LLDP snooping with LAG

### ISSUE THREAD

**Issue by italobusi** [FabioPeruzzini/actn-poi#74]
Add analysis on how LLDP snooping works with LAG

**Comment by italobusi** [comment]
**[2022-05-17 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-05-17.md)**

- [ ] @jbrentfoster : check that it is possible to configure LLDP snooping on each member of the LAG

**Comment by jbrentfoster** [comment]
I tested this today.  Cisco IOS-XR is running LLDP session on each interface and also represents the LAG bundle.  Here is sample:

`RP/0/RP0/CPU0:c8k-2#show lldp neighbors
Mon Jun 13 19:01:13.165 UTC
Capability codes:
        (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
        (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other

Device ID       Local Intf                      Hold-time  Capability      Port ID
c8k-1           FourHundredGigE0/0/0/0          120        R               Bundle-Ether12
c8k-1           FourHundredGigE0/0/0/0          120        R               FourHundredGigE0/0/0/0
c8k-1           FourHundredGigE0/0/0/1          120        R               FourHundredGigE0/0/0/1

Total entries displayed: 3

`

Just to check the behavior, I logged in to the router on the other side and shut down the second interface.  After the LLDP time-out period only one member link is remaining.

`RP/0/RP0/CPU0:c8k-2#show lldp neighbors
Mon Jun 13 19:03:01.226 UTC
Capability codes:
        (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
        (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other

Device ID       Local Intf                      Hold-time  Capability      Port ID
c8k-1           FourHundredGigE0/0/0/0          120        R               Bundle-Ether12
c8k-1           FourHundredGigE0/0/0/0          120        R               FourHundredGigE0/0/0/0

Total entries displayed: 2

`

**Comment by jbrentfoster** [comment]
I have confirmed that each router sends LLDP packets for the individual bundle member links with the source address of the router interface and the name of the interface (such as "GigabitEthernet0/0/0/7".

Also, by default each router sends LLDP packets on one of the member links with source address of the bundle interface and with the “Bundle-Ether” interface name.

However, this behavior can be disabled as shown:
```
interface Bundle-Ether10
 ipv4 address 10.10.10.1 255.255.255.252
 lldp
  transmit disable
```

After disabling LLDP on the Bundle interface, the LLDP entry is no longer in the table as shown below.
```
RP/0/RP0/CPU0:xr9kv-201#show lldp neigh
Tue Jun 21 22:15:55.475 UTC
Capability codes:
        (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
        (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other

Device ID       Local Intf                      Hold-time  Capability      Port ID
xr9kv-200.virl.info GigabitEthernet0/0/0/7          120        R               GigabitEthernet0/0/0/7
xr9kv-200.virl.info GigabitEthernet0/0/0/8          120        R               GigabitEthernet0/0/0/8
```
Also, the packet captures verify that these packets are no longer being sent with “Bundle-Ether” interface name and source MAC address.

[LLDP_Testing_1.0.docx](https://github.com/FabioPeruzzini/actn-poi/files/8968830/LLDP_Testing_1.0.docx)

Attached the full report with captures.

**Comment by italobusi** [comment]
**[2022-06-28 ACTN POI Call (Slot 2)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-06-28.md)**

The cross-layer link discovery is based only on the LLDP packets being sent on the LAG members (Aggregation Ports).

LLDP can be enabled on LAG members (Aggregation Ports) as well as on LAG groups (Aggregated Ports). If LLDP is enabled on both LAG members and groups, two types of LLDP packets are transmitted on some Ethernet interfaces from the routers and received by the ROADMs: one sent on the LAG member (Aggregation Port) and one sent on the LAG group (Aggregated Port)

To avoid this ambiguity, one possibility is to disable LLDP for the LAG group and enable LLDP only for the LAG members. This should not be an issue since the LAG group is configured by the MDSC.

Another option is to rely on other mechanisms (e.g., the Port type field in the Link Aggregation TLV defined in Annex F of IEEE 8012.1AX-2015) that allow the ROADM identify which LLDP packets have been transmitted on the LAG member (Aggregation Port) or on the LAG group (Aggregated Port).

- [ ] Italo: update the text in PR#90 accordingly
