### ISSUE TITLE
Alignment with "draft-lee-teas-actn-poi-applicability-00"

### ISSUE THREAD

**Issue by FabioPeruzzini** [FabioPeruzzini/actn-poi#8]
As previously agreed, integration of the part relevant to Packet Optical Integration of the draft “Packet Optical Integration (POI) Use Cases for Abstraction and Control of TE Networks (ACTN)” in the current proposal

**Comment by italobusi** [comment]
@FabioPeruzzini @dancecca : I think this issue has been closed with pull request #15 

What do you think?
Can we close it?
